### ISSUE TITLE
Unable to install on sf4 - Attempted to load class "GridSourceCompilerPass" from namespace 

### ISSUE THREAD

**Issue by salamichel** [mmucklo/DtcQueueBundle#117]
When `composer require mmucklo/queue-bundle` i'm getting ' Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "GridSourceCompilerPass" from namespace "Dtc\GridBundle\DependencyInjection\Compiler".'

I'm under symfony 4.3

Regards
--------

$ composer require mmucklo/queue-bundle
Using version ^6.0 for mmucklo/queue-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.3.*"
Nothing to install or update
Generating autoload files
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "GridSourceCompilerPass" from namespace "Dtc\GridBundle\DependencyInjection\Compiler".
!!  Did you forget a "use" statement for another namespace? in C:\wamp64\www\gdh.4\vendor\mmucklo\queue-bundle\DependencyInjection\Compiler\WorkerCompilerPass.php:159
!!  Stack trace:
!!  #0 C:\wamp64\www\gdh.4\vendor\mmucklo\queue-bundle\DependencyInjection\Compiler\WorkerCompilerPass.php(54): Dtc\QueueBundle\DependencyInjection\Compiler\WorkerCompilerPass->addLiveJobs(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
!!  #1 C:\wamp64\www\gdh.4\vendor\symfony\dependency-injection\Compiler\Compiler.php(95): Dtc\QueueBundle\DependencyInjection\Compiler\WorkerCompilerPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
!!  #2 C:\wamp64\www\gdh.4\vendor\symfony\dependency-injection\ContainerBuilder.php(756): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\Co in C:\wamp64\www\gdh.4\vendor\mmucklo\queue-bundle\DependencyInjection\Compiler\WorkerCompilerPass.php on line 159
!!
Script @auto-scripts was called via post-update-cmd

**Comment by salamichel** [comment]
Found package was missing https://github.com/mmucklo/DtcGridBundle
